site_name: "Zenaura Documentation"
theme:
  name: "material"
  repo_url: https://github.com/squidfunk/mkdocs-material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  font:
    text: Roboto
    code: Roboto Mono 
  features:
  - content.code.annotate
  - content.code.highlight
  - content.code.prettify
  - content.code.copy
  - content.tabs.link
  - header.autohide
  - header.search
  - header.title
  - navigation.instant
  - navigation.sections
  - navigation.tabs
  - navigation.top
  - navigation.tracking
  - search.suggest
  - search.highlight
  - toc.integrate

  language: en
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  nav: 
    - Quick Start Guide: quick.md
    - Documentation: docs.md 
    - Api Reference:
      - Algorithm:
          - Algorithm : algorithm.md 
    - Examples: examples.md
    - Advanced Guide: advanced.md 
    - Contributing: contributing.md
    - License: license.md
    - Changelog: changelog.md
    - About: about.md
    - FAQ: faq.md
 
plugins:
  - search
  - mkdocstrings


extra:
  generator: false

extra_css:
  - stylesheets/extra.css